kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: build
    image: golang
    pull: if-not-exists
    environment:
      GOPROXY: https://goproxy.cn,https://goproxy.io,direct
    commands:
      - go build -tags netgo .

  - name: publish
    image: plugins/docker
    pull: if-not-exists
    settings:
      auto_tag: true
      repo: zlyuan/zdrone-build-webhook
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
